---
title: "Homework_4"
author: "Grant Erlandson"
date: "October 24, 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(tidyr)
library(readr)
library(dplyr)
library(broom)
library(purrr)
library(ggplot2)
library(ggfortify)
library(ggthemes)
library(ggmap)
library(stringr)
```

```{r list files}
list.files("../Data/")
```

```{r read in data}
homicides <- read.csv("../Data/homicide-data.csv")
```

```{r new column}
homicides2 <- homicides %>% 
  unite(city_name, city, state, sep = ", ")
```

```{r unslolved data frame}
unsolved <- homicides %>% 
  select(city, disposition) %>% 
  mutate(solved = disposition == "Closed by arrest") %>% 
  group_by(city) %>% 
  summarize(n_homicides = n(), n_unsolved = sum(solved))
```

```{r baltimore prop test}
baltimore <- unsolved %>% 
  filter(city == "Baltimore")
baltimore_prop <- prop.test(x = baltimore$n_unsolved,
          n = baltimore$n_homicides)
tidy(baltimore_prop)
```

```{r all cities prop test}
unsolved <- unsolved %>% 
  mutate(test = map2(n_unsolved, n_homicides, ~ prop.test(.x, n = .y))) %>% 
  mutate(test = map(test, ~ tidy(.x))) %>% 
  unnest(.drop = TRUE) %>% 
  select(city, estimate, conf.low, conf.high)
```

```{reordering proportions}
unsolved_plot <- unsolved %>%
  mutate(city = (fct_reorder(.f = city, .x = estimate, .desc = FALSE)))
```
